/* ===================================================================
   L0 基础词库（零基础起步）· 批次 1
   日常 + 办公高频词，prepend 到 VOCAB 最前，让初学者先学基础。
   格式精简：无音标（用 App ▶ 听发音），保留 词/词性/中文/双语例句。
   =================================================================== */
(function(){
const L0 = [
/* ===== 基础动词 ===== */
["基础动词","be","v.","是；在","I am a marketer.","我是一名营销人。"],
["基础动词","have","v.","有","I have a meeting at 3.","我3点有个会。"],
["基础动词","do","v.","做","What do you do?","你做什么工作？"],
["基础动词","go","v.","去","I go to work by metro.","我坐地铁去上班。"],
["基础动词","come","v.","来","Can you come to the meeting?","你能来开会吗？"],
["基础动词","make","v.","做；制作","Let's make a plan.","我们做个计划。"],
["基础动词","get","v.","得到；拿到","I'll get the report today.","我今天会拿到报告。"],
["基础动词","take","v.","拿；花费(时间)","It takes two days.","这需要两天。"],
["基础动词","give","v.","给","Give me a minute.","给我一分钟。"],
["基础动词","want","v.","想要","I want to learn English.","我想学英语。"],
["基础动词","need","v.","需要","I need your help.","我需要你的帮助。"],
["基础动词","like","v.","喜欢","I like this idea.","我喜欢这个想法。"],
["基础动词","know","v.","知道","I don't know yet.","我还不知道。"],
["基础动词","think","v.","认为；想","I think it's a good plan.","我认为这是个好计划。"],
["基础动词","see","v.","看见；明白","I see what you mean.","我明白你的意思。"],
["基础动词","look","v.","看","Look at this number.","看这个数字。"],
["基础动词","find","v.","找到","I can't find the file.","我找不到文件。"],
["基础动词","use","v.","使用","We use this tool every day.","我们每天用这个工具。"],
["基础动词","work","v.","工作；起作用","This plan works.","这个方法管用。"],
["基础动词","help","v.","帮助","Can you help me?","你能帮我吗？"],
["基础动词","start","v.","开始","Let's start now.","我们现在开始。"],
["基础动词","stop","v.","停止","We should stop here.","我们应该停在这里。"],
["基础动词","try","v.","尝试","Let me try again.","让我再试一次。"],
["基础动词","ask","v.","问；请求","Can I ask a question?","我能问个问题吗？"],
["基础动词","tell","v.","告诉","Tell me more.","跟我多说说。"],
["基础动词","say","v.","说","What did she say?","她说了什么？"],
["基础动词","talk","v.","谈；聊","Let's talk later.","我们待会儿聊。"],
["基础动词","call","v.","打电话；称呼","I'll call you tomorrow.","我明天打给你。"],
["基础动词","send","v.","发送","I'll send the email now.","我现在发邮件。"],
["基础动词","meet","v.","见面","Nice to meet you.","很高兴见到你。"],
["基础动词","keep","v.","保持；继续","Keep up the good work.","继续保持。"],
["基础动词","change","v.","改变","We changed the plan.","我们改了计划。"],
["基础动词","check","v.","检查；核对","Let me check the data.","让我核对下数据。"],
["基础动词","finish","v.","完成","I'll finish it by Friday.","我周五前完成。"],
["基础动词","learn","v.","学习","I want to learn fast.","我想学得快。"],
["基础动词","show","v.","展示","Let me show you.","我给你看。"],
["基础动词","bring","v.","带来","Please bring the report.","请把报告带来。"],
["基础动词","move","v.","移动；推进","Let's move forward.","我们往前推进。"],
["基础动词","open","v.","打开","Open the file, please.","请打开文件。"],
["基础动词","close","v.","关闭","Please close the door.","请关门。"],
["基础动词","buy","v.","买","Users buy it online.","用户在线上买。"],
["基础动词","sell","v.","卖","We sell it on Tmall.","我们在天猫卖。"],
["基础动词","pay","v.","付款","The client pays monthly.","客户按月付款。"],
["基础动词","spend","v.","花费","We spend too much.","我们花得太多了。"],
["基础动词","save","v.","节省；保存","This saves time.","这能省时间。"],
["基础动词","plan","v.","计划","We plan to launch in June.","我们计划6月上线。"],
["基础动词","add","v.","增加；添加","Let's add one more.","我们再加一个。"],
["基础动词","choose","v.","选择","Choose the best one.","选最好的那个。"],
["基础动词","decide","v.","决定","We need to decide today.","我们今天得决定。"],
["基础动词","agree","v.","同意","I agree with you.","我同意你。"],
["基础动词","understand","v.","理解","Do you understand?","你理解了吗？"],
["基础动词","remember","v.","记得","Remember to follow up.","记得跟进。"],
["基础动词","explain","v.","解释","Let me explain.","让我解释下。"],
["基础动词","mean","v.","意思是","What do you mean?","你什么意思？"],
["基础动词","feel","v.","感觉","I feel good about it.","我感觉不错。"],
["基础动词","wait","v.","等待","Please wait a moment.","请稍等。"],
["基础动词","let","v.","让","Let me know.","告诉我一声。"],
["基础动词","put","v.","放","Put it here.","放这里。"],
["基础动词","read","v.","读","Please read this.","请读一下这个。"],
["基础动词","write","v.","写","I'll write it down.","我记下来。"],
["基础动词","grow","v.","增长","Sales grow fast.","销售增长很快。"],
["基础动词","improve","v.","改善","We need to improve.","我们需要改进。"],

/* ===== 基础名词 ===== */
["基础名词","time","n.","时间","Do you have time?","你有时间吗？"],
["基础名词","day","n.","天","Have a good day.","祝你愉快。"],
["基础名词","week","n.","周","See you next week.","下周见。"],
["基础名词","month","n.","月","This month is busy.","这个月很忙。"],
["基础名词","year","n.","年","Happy new year.","新年快乐。"],
["基础名词","work","n.","工作","I have a lot of work.","我有很多工作。"],
["基础名词","job","n.","工作；职位","I love my job.","我喜欢我的工作。"],
["基础名词","team","n.","团队","My team is small.","我的团队不大。"],
["基础名词","company","n.","公司","Our company is growing.","我们公司在成长。"],
["基础名词","office","n.","办公室","I'm at the office.","我在办公室。"],
["基础名词","meeting","n.","会议","The meeting is at 2.","会议2点开。"],
["基础名词","project","n.","项目","This project is hard.","这个项目很难。"],
["基础名词","idea","n.","主意；想法","That's a great idea.","好主意。"],
["基础名词","problem","n.","问题(难题)","No problem.","没问题。"],
["基础名词","question","n.","问题(疑问)","I have a question.","我有个问题。"],
["基础名词","answer","n.","答案","I don't have the answer.","我没有答案。"],
["基础名词","money","n.","钱","It costs money.","这要花钱。"],
["基础名词","price","n.","价格","The price is too high.","价格太高了。"],
["基础名词","number","n.","数字","Check the numbers.","核对下数字。"],
["基础名词","data","n.","数据","The data looks good.","数据看起来不错。"],
["基础名词","report","n.","报告","Send me the report.","把报告发我。"],
["基础名词","email","n.","邮件","I got your email.","我收到你邮件了。"],
["基础名词","phone","n.","电话","Call my phone.","打我电话。"],
["基础名词","computer","n.","电脑","My computer is slow.","我电脑很慢。"],
["基础名词","file","n.","文件","Open the file.","打开文件。"],
["基础名词","document","n.","文档","Review this document.","看下这个文档。"],
["基础名词","product","n.","产品","Our product is new.","我们产品是新的。"],
["基础名词","customer","n.","顾客","The customer is happy.","顾客很满意。"],
["基础名词","market","n.","市场","The market is big.","市场很大。"],
["基础名词","content","n.","内容","We make content daily.","我们每天做内容。"],
["基础名词","plan","n.","计划","What's the plan?","计划是什么？"],
["基础名词","goal","n.","目标","Our goal is clear.","我们目标清晰。"],
["基础名词","result","n.","结果","The results are good.","结果不错。"],
["基础名词","reason","n.","原因","What's the reason?","原因是什么？"],
["基础名词","example","n.","例子","Give me an example.","给我举个例子。"],
["基础名词","way","n.","方法；方式","That's the best way.","那是最好的办法。"],
["基础名词","thing","n.","事情；东西","One more thing.","还有一件事。"],
["基础名词","people","n.","人(复数)","People love it.","大家很喜欢。"],
["基础名词","user","n.","用户","Users come from search.","用户来自搜索。"],
["基础名词","detail","n.","细节","Send me the details.","把细节发我。"],
["基础名词","plan B","n.","备选方案","Do we have a plan B?","我们有备选方案吗？"],
["基础名词","note","n.","笔记；便条","I'll take notes.","我做下笔记。"],
["基础名词","feedback","n.","反馈","Thanks for the feedback.","谢谢反馈。"],
["基础名词","update","n.","更新；进展","Any update?","有进展吗？"],
["基础名词","question time","n.","提问时间","Let's leave question time.","留点提问时间。"],
["基础名词","week day","n.","工作日","On weekdays I'm busy.","工作日我很忙。"],
["基础名词","weekend","n.","周末","Have a nice weekend.","周末愉快。"],
["基础名词","lunch","n.","午餐","Let's get lunch.","我们去吃午饭。"],
["基础名词","break","n.","休息","Let's take a break.","我们休息一下。"],
["基础名词","manager","n.","经理","Ask the manager.","问下经理。"],

/* ===== 基础形容词 ===== */
["基础形容词","good","adj.","好的","This is good news.","这是好消息。"],
["基础形容词","bad","adj.","坏的","It's not bad.","还不错。"],
["基础形容词","big","adj.","大的","It's a big chance.","这是个大机会。"],
["基础形容词","small","adj.","小的","A small problem.","小问题。"],
["基础形容词","new","adj.","新的","A new product.","一个新产品。"],
["基础形容词","old","adj.","旧的；老的","The old plan failed.","旧计划失败了。"],
["基础形容词","high","adj.","高的","High quality.","高质量。"],
["基础形容词","low","adj.","低的","Low cost.","低成本。"],
["基础形容词","fast","adj.","快的","A fast result.","见效快。"],
["基础形容词","slow","adj.","慢的","Sales are slow.","销售很慢。"],
["基础形容词","easy","adj.","容易的","It's easy to use.","很好用。"],
["基础形容词","hard","adj.","难的；硬的","This is hard.","这很难。"],
["基础形容词","important","adj.","重要的","This is important.","这很重要。"],
["基础形容词","clear","adj.","清楚的","Is it clear?","清楚了吗？"],
["基础形容词","ready","adj.","准备好的","I'm ready.","我准备好了。"],
["基础形容词","busy","adj.","忙的","I'm busy today.","我今天很忙。"],
["基础形容词","free","adj.","空闲的；免费的","Are you free now?","你现在有空吗？"],
["基础形容词","sure","adj.","确定的","Are you sure?","你确定吗？"],
["基础形容词","right","adj.","对的；右","You're right.","你是对的。"],
["基础形容词","wrong","adj.","错的","Something is wrong.","有点不对劲。"],
["基础形容词","same","adj.","相同的","The same as before.","和之前一样。"],
["基础形容词","different","adj.","不同的","A different way.","另一种方式。"],
["基础形容词","early","adj.","早的","I'm early today.","我今天早到了。"],
["基础形容词","late","adj.","晚的；迟的","Sorry I'm late.","抱歉我迟到了。"],
["基础形容词","long","adj.","长的","A long meeting.","一个很长的会。"],
["基础形容词","short","adj.","短的","Keep it short.","简短一点。"],
["基础形容词","strong","adj.","强的","Strong results.","强劲的结果。"],
["基础形容词","cheap","adj.","便宜的","It's cheap.","它很便宜。"],
["基础形容词","expensive","adj.","贵的","Too expensive.","太贵了。"],
["基础形容词","possible","adj.","可能的","Is it possible?","有可能吗？"],
["基础形容词","real","adj.","真实的","Real users.","真实用户。"],
["基础形容词","main","adj.","主要的","The main point.","主要的点。"],
["基础形容词","next","adj.","下一个","The next step.","下一步。"],
["基础形容词","last","adj.","最后的；上一个","Last week.","上周。"],
["基础形容词","whole","adj.","整个的","The whole team.","整个团队。"],
["基础形容词","enough","adj.","足够的","That's enough.","够了。"],
["基础形容词","great","adj.","很棒的","Great job!","干得好！"],
["基础形容词","nice","adj.","好的；友善的","Nice to meet you.","很高兴见到你。"],
["基础形容词","happy","adj.","开心的","I'm happy with it.","我很满意。"],
["基础形容词","sorry","adj.","抱歉的","I'm sorry.","对不起。"],
["基础形容词","careful","adj.","小心的","Be careful.","小心。"],
["基础形容词","simple","adj.","简单的","Keep it simple.","保持简单。"],
["基础形容词","clean","adj.","干净的；简洁的","A clean design.","简洁的设计。"],
["基础形容词","useful","adj.","有用的","Very useful.","很有用。"],
["基础形容词","popular","adj.","受欢迎的","A popular product.","受欢迎的产品。"],

/* ===== 时间·日期 ===== */
["时间日期","today","n./adv.","今天","Let's finish today.","今天搞定。"],
["时间日期","tomorrow","n./adv.","明天","See you tomorrow.","明天见。"],
["时间日期","yesterday","n./adv.","昨天","I sent it yesterday.","我昨天发的。"],
["时间日期","now","adv.","现在","Let's start now.","现在开始。"],
["时间日期","later","adv.","稍后","Talk to you later.","回头聊。"],
["时间日期","soon","adv.","很快","I'll reply soon.","我很快回复。"],
["时间日期","morning","n.","早上","Good morning.","早上好。"],
["时间日期","afternoon","n.","下午","Good afternoon.","下午好。"],
["时间日期","evening","n.","晚上","Good evening.","晚上好。"],
["时间日期","tonight","n./adv.","今晚","I'll work tonight.","我今晚加班。"],
["时间日期","Monday","n.","周一","The meeting is Monday.","会议在周一。"],
["时间日期","Tuesday","n.","周二","Due on Tuesday.","周二截止。"],
["时间日期","Wednesday","n.","周三","Let's meet Wednesday.","周三见。"],
["时间日期","Thursday","n.","周四","I'm free Thursday.","我周四有空。"],
["时间日期","Friday","n.","周五","By Friday, please.","请在周五前。"],
["时间日期","Saturday","n.","周六","I rest on Saturday.","我周六休息。"],
["时间日期","Sunday","n.","周日","Sunday is my day off.","周日是我的休息日。"],
["时间日期","hour","n.","小时","It takes an hour.","需要一小时。"],
["时间日期","minute","n.","分钟","In five minutes.","五分钟后。"],
["时间日期","deadline","n.","截止日期","The deadline is today.","今天截止。"],
["时间日期","schedule","n.","日程","Check my schedule.","看下我的日程。"],
["时间日期","date","n.","日期","What's the date?","几号了？"],
["时间日期","quarter","n.","季度","This quarter's goal.","本季度目标。"],
["时间日期","period","n.","时期；阶段","During this period.","在这段时间。"],
["时间日期","season","n.","季节；旺季","The peak season.","旺季。"],

/* ===== 数字·数量 ===== */
["数字数量","one","num.","一","One more thing.","还有一件事。"],
["数字数量","two","num.","二","Give me two days.","给我两天。"],
["数字数量","three","num.","三","Three options.","三个选项。"],
["数字数量","ten","num.","十","Ten percent up.","涨了10%。"],
["数字数量","hundred","num.","百","A hundred notes.","一百篇笔记。"],
["数字数量","thousand","num.","千","Ten thousand fans.","一万粉丝。"],
["数字数量","million","num.","百万","Two million reads.","两百万阅读。"],
["数字数量","first","adj.","第一","The first step.","第一步。"],
["数字数量","second","adj.","第二","The second option.","第二个选项。"],
["数字数量","third","adj.","第三","The third week.","第三周。"],
["数字数量","half","n.","一半","Half of the budget.","一半的预算。"],
["数字数量","double","v./adj.","翻倍","Double the search.","搜索翻倍。"],
["数字数量","percent","n.","百分比","Up ten percent.","涨10%。"],
["数字数量","more","adj.","更多","We need more data.","我们需要更多数据。"],
["数字数量","less","adj.","更少","Spend less.","少花点。"],
["数字数量","most","adj.","大多数","Most users like it.","大多数用户喜欢。"],
["数字数量","few","adj.","很少","A few problems.","一些小问题。"],
["数字数量","many","adj.","许多","Too many tasks.","任务太多。"],
["数字数量","much","adj.","许多(不可数)","How much is it?","多少钱？"],
["数字数量","total","n./adj.","总计","The total is 300.","总共300。"],
["数字数量","average","n./adj.","平均","On average.","平均来说。"],
["数字数量","about","adv.","大约","About 16 times.","大约16倍。"],
["数字数量","over","prep.","超过","Over two million.","超过两百万。"],
["数字数量","under","prep.","低于","Under 30 yuan.","低于30元。"],
["数字数量","each","adj.","每一个","Each note costs 500.","每篇500。"],

/* ===== 办公·会议 ===== */
["办公会议","agenda","n.","议程","Here's the agenda.","这是议程。"],
["办公会议","task","n.","任务","My task list.","我的任务清单。"],
["办公会议","update","v.","更新；汇报进展","I'll update you.","我会跟你同步。"],
["办公会议","approve","v.","批准","Please approve it.","请批准。"],
["办公会议","confirm","v.","确认","Can you confirm?","你能确认吗？"],
["办公会议","cancel","v.","取消","Let's cancel the call.","电话会取消吧。"],
["办公会议","reschedule","v.","改期","Can we reschedule?","能改期吗？"],
["办公会议","attend","v.","参加","I'll attend the meeting.","我会参加会议。"],
["办公会议","prepare","v.","准备","Let me prepare it.","让我准备一下。"],
["办公会议","discuss","v.","讨论","Let's discuss this.","我们讨论下这个。"],
["办公会议","review","v.","审阅；复盘","Let's review the data.","我们看下数据。"],
["办公会议","share","v.","分享","I'll share my screen.","我分享屏幕。"],
["办公会议","join","v.","加入","Join the call, please.","请加入电话会。"],
["办公会议","forward","v.","转发","I'll forward the email.","我转发邮件。"],
["办公会议","reply","v.","回复","Please reply by noon.","请中午前回复。"],
["办公会议","follow up","phr.","跟进","I'll follow up.","我会跟进。"],
["办公会议","catch up","phr.","碰头；同步","Let's catch up later.","回头同步下。"],
["办公会议","sign off","phr.","签字批准","I need sign-off.","我需要批准。"],
["办公会议","on time","phr.","准时","Please be on time.","请准时。"],
["办公会议","overtime","n.","加班","I worked overtime.","我加班了。"],
["办公会议","schedule","v.","安排","Let's schedule a call.","我们约个电话会。"],
["办公会议","assign","v.","分配","I'll assign the task.","我来分配任务。"],
["办公会议","handle","v.","处理","I'll handle it.","我来处理。"],
["办公会议","manage","v.","管理","I manage the team.","我管理团队。"],
["办公会议","support","v.","支持","I'll support you.","我支持你。"],
["办公会议","contact","v.","联系","Contact me anytime.","随时联系我。"],
["办公会议","arrange","v.","安排","I'll arrange it.","我来安排。"],
["办公会议","note down","phr.","记下来","Let me note it down.","我记一下。"],
["办公会议","wrap up","phr.","收尾","Let's wrap up.","我们收尾吧。"],
["办公会议","kick off","phr.","启动","Let's kick off.","我们开始吧。"],
["办公会议","priority","n.","优先事项","It's a top priority.","这是头等大事。"],
["办公会议","progress","n.","进展","Good progress.","进展不错。"],
["办公会议","issue","n.","问题","Any issues?","有什么问题吗？"],
["办公会议","solution","n.","解决方案","I have a solution.","我有个方案。"],
["办公会议","decision","n.","决定","It's your decision.","由你决定。"],
["办公会议","approval","n.","批准","Waiting for approval.","等待批准。"],
["办公会议","minutes","n.","会议纪要","I'll send the minutes.","我发会议纪要。"],
["办公会议","draft","n.","草稿","Here's a draft.","这是个草稿。"],
["办公会议","version","n.","版本","The final version.","最终版本。"],
["办公会议","template","n.","模板","Use this template.","用这个模板。"],

/* ===== 沟通·客套 ===== */
["沟通客套","hello","int.","你好","Hello, everyone.","大家好。"],
["沟通客套","hi","int.","嗨","Hi, how are you?","嗨，你好吗？"],
["沟通客套","thanks","int.","谢谢","Thanks a lot.","非常感谢。"],
["沟通客套","please","adv.","请","Please go ahead.","请继续。"],
["沟通客套","welcome","int.","不客气；欢迎","You're welcome.","不客气。"],
["沟通客套","goodbye","int.","再见","Goodbye, see you.","再见。"],
["沟通客套","excuse me","phr.","打扰一下","Excuse me, a question.","打扰一下，问个问题。"],
["沟通客套","no problem","phr.","没问题","No problem at all.","完全没问题。"],
["沟通客套","of course","phr.","当然","Of course, I can.","当然可以。"],
["沟通客套","sure","int.","当然可以","Sure, go ahead.","当然，请。"],
["沟通客套","my pleasure","phr.","我的荣幸","My pleasure.","乐意效劳。"],
["沟通客套","take care","phr.","保重","Take care!","保重！"],
["沟通客套","good luck","phr.","祝好运","Good luck!","祝你好运！"],
["沟通客套","congratulations","int.","恭喜","Congratulations!","恭喜！"],
["沟通客套","how are you","phr.","你好吗","How are you doing?","你最近怎么样？"],
["沟通客套","nice to meet you","phr.","很高兴认识你","Nice to meet you.","很高兴认识你。"],
["沟通客套","see you","phr.","回头见","See you tomorrow.","明天见。"],
["沟通客套","by the way","phr.","顺便说","By the way, one more thing.","顺便说，还有件事。"],
["沟通客套","let me know","phr.","告诉我一声","Let me know anytime.","随时告诉我。"],
["沟通客套","go ahead","phr.","请继续","Go ahead, please.","请说。"],
["沟通客套","got it","phr.","明白了","Got it, thanks.","明白了，谢谢。"],
["沟通客套","make sense","phr.","讲得通","That makes sense.","有道理。"],
["沟通客套","fair enough","phr.","有道理；可以","Fair enough.","有道理。"],
["沟通客套","absolutely","adv.","绝对地；当然","Absolutely!","当然！"],
["沟通客套","exactly","adv.","正是","Exactly!","正是如此！"],
["沟通客套","no worries","phr.","别担心","No worries.","没事。"],
["沟通客套","good point","phr.","说得好","Good point.","说得好。"],
["沟通客套","I agree","phr.","我同意","I totally agree.","我完全同意。"],
["沟通客套","I'm not sure","phr.","我不确定","I'm not sure yet.","我还不确定。"],
["沟通客套","let's do it","phr.","就这么办","Let's do it.","就这么办。"],

/* ===== 连接·常用 ===== */
["连接常用","and","conj.","和","Fast and cheap.","又快又便宜。"],
["连接常用","but","conj.","但是","Good, but slow.","好，但是慢。"],
["连接常用","or","conj.","或者","Today or tomorrow?","今天还是明天？"],
["连接常用","so","conj.","所以","It's late, so let's stop.","太晚了，所以先停。"],
["连接常用","because","conj.","因为","Because of the budget.","因为预算。"],
["连接常用","if","conj.","如果","If you agree, we start.","如果你同意，我们就开始。"],
["连接常用","when","conj.","当…时","When you're ready.","等你准备好。"],
["连接常用","then","adv.","然后","First this, then that.","先这个，然后那个。"],
["连接常用","also","adv.","也","I also think so.","我也这么想。"],
["连接常用","however","adv.","然而","However, there's a risk.","然而有个风险。"],
["连接常用","for example","phr.","例如","For example, RED.","例如小红书。"],
["连接常用","in addition","phr.","另外","In addition, it's cheap.","另外，它很便宜。"],
["连接常用","at least","phr.","至少","At least one month.","至少一个月。"],
["连接常用","by the way","phr.","顺便","By the way, it's done.","顺便说，搞定了。"],
["连接常用","in short","phr.","简而言之","In short, it works.","简而言之，可行。"],
["连接常用","actually","adv.","其实","Actually, I disagree.","其实我不同意。"],
["连接常用","maybe","adv.","也许","Maybe next week.","也许下周。"],
["连接常用","probably","adv.","大概","Probably yes.","大概是的。"],
["连接常用","usually","adv.","通常","I usually start at 9.","我通常9点开始。"],
["连接常用","always","adv.","总是","I always check first.","我总是先检查。"],
["连接常用","never","adv.","从不","Never mind.","没关系。"],
["连接常用","already","adv.","已经","It's already done.","已经做完了。"],
["连接常用","still","adv.","仍然","Still in progress.","还在进行中。"],
["连接常用","instead","adv.","代替","Let's do this instead.","不如改做这个。"],
["连接常用","especially","adv.","尤其","Especially on weekends.","尤其是周末。"],
];
// 转成对象并 prepend 到 VOCAB 最前（让基础词先学）
const objs = L0.map(a=>({lv:0,cat:a[0],w:a[1],pos:a[2],cn:a[3],ex:a[4],exCn:a[5],ph:""}));
if(typeof VOCAB!=='undefined') VOCAB.unshift(...objs);
})();
